import type { NextPage } from "next";
import Head from "next/head";

import Header from "../components/Header";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Calendar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header clickBack={() => {} } clickNext={() => {}} showInfoModal={() => {}} />

      <main>
        <h1>hello mom!</h1>
      </main>
    </>
  );
};

export default Home;
