-- AlterTable
ALTER TABLE "events" ADD COLUMN     "event_end_date" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "event_end_time" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "event_location" VARCHAR(200) NOT NULL DEFAULT '',
ADD COLUMN     "event_start_date" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "event_start_time" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP;
